server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://192.168.109.132:3306/offline_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: bhps
    password: bhps
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.agilestar.*.pojo

